{% set data=load_setup_py_data() %}

package:
  name: oviraptor
  version: {{ data['version'] }}

source:
  path: ../../

build:
  number: 0

requirements:
  build:
    - python {{ python }}
    {% for dep in data.get("install_requires", []) -%}
    - {{ dep.lower() }}
    {% endfor %}

  run:
    - python
    {% for dep in data.get("install_requires", []) -%}
    - {{ dep.lower() }}
    {% endfor %}
    - snakemake-minimal
    - samtools
    - sambamba
    - mosdepth
    - minimap2
    - bcftools
    - bedtools
    - pysam  # to process the BAM file for lumpy
    - awscli  # to download the reference fasta

test:
  commands:
    - oviraptor --help

about:
  home: {{ data['url'] }}
  license: {{ data['license'] }}
  summary: {{ data['description'] }}
