{% set data=load_setup_py_data() %}

package:
  name: oviraptor
  version: {{ data['version'] }}

source:
  path: ../../

build:
  number: 0
  noarch: python

requirements:
  build:
    - python >=3.6
    {% for dep in data.get("install_requires", []) -%}
    - {{ dep.lower() }}
    {% endfor %}

  run:
    - python >=3.6
    {% for dep in data.get("install_requires", []) -%}
    - {{ dep.lower() }}
    {% endfor %}
    - snakemake-minimal
    - samtools
    - sambamba
    - mosdepth >=0.2.9
    - bwa
    - bcftools
    - bedtools
    - awscli  # to download the reference fasta

test:
  commands:
    - oviraptor --help

about:
  home: {{ data['url'] }}
  license: {{ data['license'] }}
  summary: {{ data['description'] }}
