{% set version=load_setup_py_data().get('version') %}

package:
  name: oncoviruses
  version: "{{ version }}"

source:
  path: ../../

build:
  number: 0

requirements:
  build:
    - python ==3.7.*
    {% for dep in data.install_requires -%}
    - {{ dep.lower() }}
    {% endfor %}
    - ngs_utils
  run:
    - python ==3.7.*
    {% for dep in data.install_requires -%}
    - {{ dep.lower() }}
    {% endfor %}
    - snakemake
    - samtools
    - sambamba
    - mosdepth
    - bwa
    - bcftools
    - ngs_utils

test:
  commands:
    - oncoviruses --help

about:
  home: "{{ data.url }}"
  license: "GNU General Public License v3 (GPLv3)"
  license_family: GPL3
  summary: "{{ data.description }}"
